### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Spuds**
Here are some master branch updates. 

- Added basic namespace for OpenImporter and Importers to help avoid problems, or create them !
- Added mybb 1.8, smf 2.1 and Wedge (from the ones TE added on the site
- Changed OI use of $config to $oi_config .. global config is "born" in the fetchsettings call, something to fix in dev so its not so reliant on that, but mybb, vb, and others expect that.
- Various random comments, mainly to help me since I was really unfamiliar with the code.
- Fixed a few bugs here and there, probably created a few with the namespace ;)
- I ran fresh install conversions of 2.1, wedge and mybb 1.8 and they seemed to work.  
- Removed some ie 5.5/6 JS support plus a few other tweaks

ETA ... and I broke the tests :crying_cat_face:

### CODE REVIEW

**Comment by emanuele45** [comment]
> ETA ... and I broke the tests :crying_cat_face:

You are a naughty boy. :sob:

**Comment by Spuds** [comment]
I've tried a few things to get them to run, all I've gotten back is a :facepunch: back ... Any ideas ??  Its a namespace issue, even though Scrutinizer says it passed, it fails to run phpunit due to not finding the classes to load.

**Comment by emanuele45** [comment]
ehhh... let's see https://travis-ci.org/emanuele45/openimporter/builds/106843228 :fingers_crossed:

**Comment by emanuele45** [comment]
I wonder why the test is taking forever to start...

Anyway, the commit is https://github.com/emanuele45/openimporter/commit/6900258fa00f7eede6ed94065072bb8f950ee9fe

It's a bit hackish the redeclaration of the ImporterException class that requires the test to be run in a separate process **and** to have setPreserveGlobalState set to false.
But it works, so it should be fine. :stuck_out_tongue:

**Comment by Spuds** [comment]
None of mine started either, but everything seemed to fail in Scrutinizer which showed it was running phpunit through redis ? ... if you check the log https://scrutinizer-ci.com/g/OpenImporter/openimporter/inspections/6195ca2c-b8c5-43bf-b95c-a6a09b7a26dd/log as an example you see its failing to find the files.

**Comment by emanuele45** [comment]
Scrutinizer looks good now:
https://scrutinizer-ci.com/g/OpenImporter/openimporter/inspections/b66cdc01-0217-4bfd-aaee-700bba7e6db2/log

Though travis doesn't want to start.

**Comment by Spuds** [comment]
I just made the commit and I'm getting Trying to @cover or @use not existing method "Lang::findLanguage". but at least it started ...

**Comment by emanuele45** [comment]
Yep, see the edit of my comment. :angel:

**Comment by Spuds** [comment]
OK now they run!  Thanks! ... But what a pain in the ass !

**Comment by emanuele45** [comment]
Ohh... that now makes sense!
I thought the builds timed out somehow.
I restarted the #100 to see if it was going to finish properly... well, it is now. I'll close the testing PR.

**Pull request merged**
