### PR TITLE
Fixes in several places

### PR DESCRIPTION
**Pull request by emanuele45**
This **may** also address #75 tough I'm not entirely sure... @margarett if you have time try this branch. ;)

### CODE REVIEW

**Comment by margarett** [comment]
Yup. After I fixed the missing path in Elk, it seems to have imported the attachments (the only 2 I had in MyBB test setup :tongue: )

I'll continue further testing ;-)

**Comment by emanuele45** [comment]
I tested this branch with an Wedge => ElkArte import and it worked with a clean install of Elk.

Oh, and @TE: do not merge this yet, it's still missing the notifications part of Wedge, that **will** require an addition or a change to the skeleton structure.

**Comment by margarett** [comment]
I have been testing only with MyBB because, well, it is already set up :tongue: and I want to build the 1.8 "source"

I will install other scripts locally in order to perform more tests ;-)

**Comment by emanuele45** [comment]
> I will install other scripts locally in order to perform more tests ;-)

No problem, I mentioned Wedge just because I was testing that one. ;)
And the "clean install" was meant for Elk, without tweaking the settings. Of course, being Wedge an SMF-based system it may be I brought some settings with the importer itself, so kind of unreliable for testin...

Okay, I have finished with the fixes for this branch.

**Comment by margarett** [comment]
Gave this branch another test from MyBB to Elk and it works fine ;-)

**Pull request merged**
