### PR TITLE
New source: IP.board 3.4.x

### PR DESCRIPTION
**Pull request by emanuele45**
Plus some adjustments to the skeletons and corresponding fixes to the various importers.

### CODE REVIEW

**Comment by margarett** [comment]
:) Great work as usual
@emanuele45 could you please check the PM I sent you at sm.org?

**Comment by emanuele45** [comment]
It's in the queue. I'll answer... sooner or later. :angel:

**Comment by emanuele45** [comment]
The importer is broken, so closing this until it's fixed.

**Comment by emanuele45** [comment]
At the best of my knowledge is not fixed... I hope.

**Pull request merged**
